utils::globalVariables(c(".n", "AirTemp", "FLOW", "LongWave", "Rain", "RelHum", "SALT", "ShortWave",
                         "Snow", "TEMP", "WindSpeed", "air_temperature", "approx", "approxfun",
                         "data_assimilation", "datetime", "day_advance", "depth", "dev.off",
                         "dnorm", "eastward_wind", "ensemble",
                         "family", "flow_number", "flow_type", "forecast", "forecast_SSS_Oxy",
                         "forecast_SSS_flow", "forecast_lower_95", "forecast_mean", "forecast_upper_95",
                         "horizon", "hour_step", "inflow_num", "max_horizon", "model_id", "new_horizon",
                         "northward_wind", "observation","observed", "outflow_num", "over", "parameter", "pdf",
                         "precipitation_flux", "predicted", "prediction", "pubDate", "pub_time", "quantile",
                         "reference_datetime", "relative_humidity", "rnorm", "runif", "saved_file",
                         "sd", "set_nml", "site_id", "str_split_fixed", "surface_downwelling_longwave_flux_in_air",
                         "surface_downwelling_shortwave_flux_in_air", "time",
                         "variable", "variable_type", "wind_speed", "write.csv",
                         "lake_directory","multi_depth", "set_names", "force_tz", "as_vector", "pub_datetime", "log_weight", "reference_date",
                         "na.omit", "max_datetime", "reference_date", "reference_date", "obs_config", "multi_depth",
                         "active_in_xmatrix", "n_non_vertical", "obs_non_vertical",
                         "working_directory", "up95", "low95", "par_init", "target_variable", "obs_sd",
                         "WindDir", "longwave_radiation", "shortwave_radiation", "temperature_2m",
                         "precipitation", "wind_speed_10m", "relative_humidity_2m", "wind_direction_10m"))
